name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Set Version
      run: |
        export VERSION=0.0.$(date +%s)
        echo "Setting version to: ${VERSION}"
        echo "::set-env name=VERSION::$VERSION"
    - name: Build & Test
      run: ./build.sh $VERSION
    - name: Create GitHub Release
      uses: anton-yurchenko/git-release@v4.1.2
      env:
          RELEASE_NAME: ${VERSION}-alpha
          PRE_RELEASE: true
          ALLOW_EMPTY_CHANGELOG: true
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      with:
        args: build/**/*/
