name: Build Powershell-Proxy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Set Version
      run: |
        export VERSION=0.0.$(date +%s)
        echo "Setting version to: ${VERSION}"
        echo "::set-env name=VERSION::$VERSION"
    - name: Build & Test
      run: ./build.sh $VERSION
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        name: $VERSION-alpha
        tag_name: $VERSION-alpha
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
         ./build/linux/powershell-proxy_linux_amd64
         ./build/win/powershell-proxy_win_amd64.exe
      env:
        GITHUB_REPOSITORY: https://github.com/thomassampson/powershell-proxy