name: Build Powershell-Proxy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  set_version:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ubuntu-latest
    steps:
    - name: Set Version
      run: |
        export VERSION=0.0.$(date +%s)
        echo "Setting version to: ${VERSION}"
        echo "::set-env name=VERSION::$VERSION"
        echo $VERSION > version.txt
    - name: Upload version
      uses: actions/upload-artifact@v2
      with:
        name: version
        path: version.txt
  test:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    needs: set_version
    runs-on: ubuntu-latest
    steps:
    - name: Download Version
      uses: actions/download-artifact@v2
      with:
        name: version
    - name: Set Version
      run: | 
        export VERSION=$(cat version.txt) 
        echo "::set-env name=VERSION::$VERSION"
        echo "Version: ${VERSION}"

    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: test
      run: ./test.sh $VERSION
  build:
    needs: test
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ubuntu-latest
    steps:
    - name: Download Version
      uses: actions/download-artifact@v2
      with:
        name: version
    - name: Set Version
      run: | 
        export VERSION=$(cat version.txt) 
        echo "::set-env name=VERSION::$VERSION"
        echo "Version: ${VERSION}"

    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: ./build.sh $VERSION
    - name: Upload Linux Version
      uses: actions/upload-artifact@v2
      with:
        name: powershell-proxy_linux_amd64
        path: ./build/linux/powershell-proxy_linux_amd64
    - name: Upload Windows Version
      uses: actions/upload-artifact@v2
      with:
        name: powershell-proxy_win_amd64.exe
        path: ./build/win/powershell-proxy_win_amd64.exe
  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Download Version
      uses: actions/download-artifact@v2
      with:
        name: version
    - name: Set Version
      run: | 
        export VERSION=$(cat version.txt) 
        echo "::set-env name=VERSION::$VERSION"
        echo "Version: ${VERSION}"
    - name: Download Linux
      uses: actions/download-artifact@v2
      with:
        name: powershell-proxy_linux_amd64
    - name: Download Windows
      uses: actions/download-artifact@v2
      with:
        name: powershell-proxy_win_amd64.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        name: ${{env.VERSION}}-alpha
        tag_name: ${{env.VERSION}}-alpha
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
         powershell-proxy_linux_amd64
         powershell-proxy_win_amd64.exe
      env:
        GITHUB_REPOSITORY: https://github.com/thomassampson/powershell-proxy